### ISSUE TITLE
unable to run setup on previous setup with winhttp.dll

### ISSUE THREAD

**Issue by Jan200101** [Foldex/r2mod_cli#10]
Currently r2mod checks for BepInEx and winhttp.dll before allowing anything to run which does not exist on a fresh install and prevents the setup from running

https://github.com/Foldex/r2mod_cli/blob/e9ef3d3b25d872edc41c72beecb1e4fcfe686908/r2mod#L131-L133

**Comment by Foldex** [comment]
On a fresh install, the check on line 132 will trigger the bepin setup, which installs BepInEx's winhttp and only after that would winhttp be checked for. Setup not triggering and hitting that would mean that you somehow have a `BepInEx` folder but no accompanying `winhttp.dll`, which would be a leftover broken install.

I've made it offer to enter setup when either winhttp or doorstop are missing instead of erroring out entirely.
