### ISSUE TITLE
Attempting to install occasionally says "Cannot parse JSON" instead of "Not a valid mod name"

### ISSUE THREAD

**Issue by Angular-Angel** [Foldex/r2mod_cli#15]
I was attempting to install MMHOOK, and because I had written it as XOXFaby instead of XoXFaby, it gave me the "Cannot parse JSON error, instead of "Not a valid mod name" error, and made things much confusing than they would otherwise be.

**Comment by Foldex** [comment]
`Not a valid mod name` is only used when trying to install something that does not match the format of a mod string. 
e.g. `r2mod install notamod` fails, but `r2mod install notamod-but-lookslikeone` is allowed.
The JSON error simply means that jq failed to return a result.
You entered a potentially valid mod name, there was just no result because of the typo. That is working as intended.
