### ISSUE TITLE
Game would not actually run with any mods installed

### ISSUE THREAD

**Issue by Angular-Angel** [Foldex/r2mod_cli#16]
The script would seem to have succeeded in installing mods, but when run, the game would be vanilla, even if run through the script and with the modded option selected. I successfully changed my enviroment variable to refer to the game, this did not make any difference.

Additionally, I tried using R2ModManager, and after doing so I found myself unable to run Risk of Rain 2 at all, even after verifying the game files, and uninstalling and reinstalling, and switching over to an empty profile in R2ModManager. Not sure if this is related.

**Comment by Angular-Angel** [comment]
Okay, so I think I figured out the crashing issue - that was related to R2ModMan, and had nothing to do with r2mod_cli. r2mod_cli still failed to apply any mods, however.

**Comment by Foldex** [comment]
Not sure if your problem is related to the latest update or not.
A lot of older mods are broken because of it. R2API hasn't been updated yet, and there's some other competing APIs cropping up, so things are up in the air regarding compatability right now. Certain mods should still work though.
After running `setup`, try installing just `wildbook-TooManyFriends-1.1.1` and see if it works, your multiplayer lobbies should allow more than 4 players with it installed. If it doesn't work, then your issue is probably unrelated to the update.

You might want to check `Steam/steamapps/common/Risk of Rain 2/BepInEx/LogOutput.log` for errors.
Also make sure BepinEx is enabled in `doorstop_config.ini` , and that `Steam/steamapps/compatdata/632360/pfx/user.reg` has an override entry for `winhttp`.
