### ISSUE TITLE
jq: error: Could not open file /tmp/r2mod/pkgs.json: No such file or directory

### ISSUE THREAD

**Issue by GameKyuubi** [Foldex/r2mod_cli#20]
```
[:~] $ r2mod setup
✦ RiskofThunder-HookGenPatcher Missing, Installing
→ Installing HookGenPatcher...
jq: error: Could not open file /tmp/r2mod/pkgs.json: No such file or directory
✖ Failed to Parse JSON for RiskofThunder-HookGenPatcher
```
followup from #19

**Comment by Foldex** [comment]
Looks like the last issue left the setup only partially completed. The safety check for hookgen patcher caught that, and tried to reinstall it, but it lacked a check for the package cache existing. Since the cache gets put in `/tmp` it does get cleared on reboot, which may have happened between your attempts here.

Since this is caused by a partially completed `setup`, you can always just remove the `$R2MOD_INSTALL_DIR/BepInEx` folder, run again, and it should fix itself. Regardless, I pushed a commit that should fix this.
