### ISSUE TITLE
Feature request: flatpak distribution

### ISSUE THREAD

**Issue by ouvoun** [Foldex/r2mod_cli#21]
This is an awesome tool, thanks for your work on it. Do you have any plans to have it be distributed via flatpak?

**Comment by Foldex** [comment]
Flatpak build is a go.
There are however some compromises/workarounds involved:
- Shell completions are installed to user owned dirs instead of the root owned ones, as flatpak cannot install to system dirs.
For Bash this should just work, but ZSH will not load the completions by default.
ZSH will need `export fpath=(${XDG_DATA_HOME:-"$HOME/.local/share"}/zsh/site-functions $fpath)` in your profile
- If using a custom install location, you will need to set flatpak overrides to allow access to those directories, which have some [caveats](https://github.com/Foldex/r2mod_cli#flatpak-1) involved.
- The `run` command obviously cannot function in the flatpak sandbox, and is disabled.

**Comment by ouvoun** [comment]
Wow absolutely awesome, thank you so much for your effort on this! Works perfectly.

Now I need to dig around to figure out why some mods aren't working as expected on Linux. 😅
