### ISSUE TITLE
Proton overrides file missing?

### ISSUE THREAD

**Issue by jayx11** [Foldex/r2mod_cli#22]
Got this warning when i ran the installer, when i launch the game using `r2mod run` and selecting "modded" the mods still dont load, assume it is related to this message and i can't find anything online on how to find the file or fix it. Script was pulled directly from AUR.
![proton over](https://user-images.githubusercontent.com/15267288/159589127-addbefbf-2403-436e-b973-419eb725e931.png)

**Comment by Foldex** [comment]
`compatdata` is where proton stores its prefixes for games, and the `user.reg` file lets us override proton's default dlls so that BepInEx is actually loaded. This file should automatically have been created if you've launched of the game.

It looks like you've exported `R2MOD_INSTALL_DIR`, but not `R2MOD_COMPAT_DIR`, you can see that the overrides file location is defaulting to `$HOME/.local/share` and not `/media/drive1`.

If you're using a custom install directory you need to point both environment variables to the appropriate locations:
`export R2MOD_COMPAT_DIR="/media/drive1/SteamLibrary/steamapps/compatdata/632360"`
should likely be what you're looking for.

**Comment by jayx11** [comment]
okay it seems to have all worked out after re-running `r2mod setup` again **after** correctly setting the ENV variables. hope this helps others with the same problem, and thanks again for the script! works awesome!
