### ISSUE TITLE
mod installing error

### ISSUE THREAD

**Issue by bgkillas** [Foldex/r2mod_cli#9]
KingEnderBrine-LobbyVotesSave and KingEnderBrine-InLobbyConfig
install in a way that bepinex cant find the right file location

**Comment by Foldex** [comment]
Looks like 7z extracts the files fine, but flattens the directory structure into the filename and puts "\\" into the filename instead of "/".
Since backslashes in Windows filenames are illegal, as they are used as directory separators, this was breaking the mods.

Since both are from the same author, it's likely that whatever the mod author is using to package their zips produces something malformed, but this could possibly be a bug within 7z itself.

Either way, I pushed a commit that should workaround this. Let me know if it doesn't work.
